// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp9fHtGhmumKr10J-Mz530KNGKoASDPCU',
    appId: '1:302823250244:web:34cd31a18a303067355f11',
    messagingSenderId: '302823250244',
    projectId: 'remidi1nalen',
    authDomain: 'remidi1nalen.firebaseapp.com',
    storageBucket: 'remidi1nalen.firebasestorage.app',
    measurementId: 'G-KNVQGHQ4T0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk6qcGgq51ZxZGTnMMpmFe1KL8W8Wh5H4',
    appId: '1:302823250244:android:24ed2b14c100a8c6355f11',
    messagingSenderId: '302823250244',
    projectId: 'remidi1nalen',
    storageBucket: 'remidi1nalen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuqLH8vjz9Gxc-mndIMvfwfOYg61siRHE',
    appId: '1:302823250244:ios:75289868ebc8c5f5355f11',
    messagingSenderId: '302823250244',
    projectId: 'remidi1nalen',
    storageBucket: 'remidi1nalen.firebasestorage.app',
    iosBundleId: 'com.example.aktivitas1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuqLH8vjz9Gxc-mndIMvfwfOYg61siRHE',
    appId: '1:302823250244:ios:75289868ebc8c5f5355f11',
    messagingSenderId: '302823250244',
    projectId: 'remidi1nalen',
    storageBucket: 'remidi1nalen.firebasestorage.app',
    iosBundleId: 'com.example.aktivitas1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCp9fHtGhmumKr10J-Mz530KNGKoASDPCU',
    appId: '1:302823250244:web:ffe64468e67ab02b355f11',
    messagingSenderId: '302823250244',
    projectId: 'remidi1nalen',
    authDomain: 'remidi1nalen.firebaseapp.com',
    storageBucket: 'remidi1nalen.firebasestorage.app',
    measurementId: 'G-D2V0CS04FZ',
  );
}
